### PR TITLE
Adding default value

### PR DESCRIPTION
**Pull request by Dizrupto**
### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/DIV-6637

### Change description ###

Adding default value to ccd-definition-processor

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by madjava — APPROVED** [review]

**Review by jacmurphy — APPROVED** [review]

**Review by jvictorcf — COMMENTED** [review]
@Dizrupto, I don't quite understand this PR.

**Review by jvictorcf — CHANGES_REQUESTED** [review]
I believe these changes need to be done on the submodule, don't they?

**Comment by jacmurphy** [comment]
@jvictorcf Unfortunately, they couldnt be done in the sub module. The spreadsheet wasnt updating. This seems to be the only way to get the most recent changes

**Review by jvictorcf — APPROVED** [review]
@Dizrupto has explained that all he's done here is to fetch the latest version of the submodule. So, happy to approve that.

**Review by yarpo — APPROVED** [review]

**Pull request merged**
