### PR TITLE
Added dynamic list for dncostoptions

### PR DESCRIPTION
**Pull request by mounikahmcts**
https://tools.hmcts.net/jira/browse/DIV-4727

### CODE REVIEW

**Comment by hosainnet** [comment]
Please ignore previous comment, we will keep master as the default and created a `prod` branch

**Comment by tchow8** [comment]
Have you tested "FieldType": "DynamicList" works yet? If it does, then I'll approve :+1:
I just saw https://tools.hmcts.net/jira/browse/RDM-4368 isn't complete yet, so just wondering.

**Comment by hosainnet** [comment]
@mounikahmcts still needed?

**Comment by mounikahmcts** [comment]
> @mounikahmcts still needed?

Closing till we get confirmation from CCD team on the data migration for this

**Pull request closed without merging**
