### PR TITLE
DIV-6753: Adding respondent service details to solicitor create event

### PR DESCRIPTION
**Pull request by Dizrupto**
### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/DIV-6753

### Change description ###

Petitioner solicitor can select respondent solicitor

**Does this PR introduce a breaking change?** (check one with "x")

```
[x] Yes
[ ] No
```

### CODE REVIEW

**Review by madjava — APPROVED** [review]
@Dizrupto You sure `caseworker-caa` is not needed anywhere here?

**Review by jvictorcf — COMMENTED** [review]
@Dizrupto, my suggestion would be to have a preparatory PR (like https://github.com/hmcts/div-ccd-definitions/pull/657) before you put your work in it.
I think it will be a lot easier to see what your changes are, then.

But, it's just my personal opinion. Feel free to disregard it.

**Review by johnoneill46 — APPROVED** [review]

**Review by yarpo — COMMENTED** [review]
Jira ticket in title of PR, please

**Review by yarpo — CHANGES_REQUESTED** [review]
Are you sure it should go to this feature toggle? Please double check with Jeremy. I have a feeling it may be released separately.

**Comment by johnoneill46** [comment]
> Are you sure it should go to this feature toggle? Please double check with Jeremy. I have a feeling it may be released separately.

@yarpo Which toggle should it go under? It's not needed for SaC and all resp Journey should be released as a single release

**Review by yarpo — APPROVED** [review]
@johnoneill46 if we know it goes together with epic "resp-journey-roles-and-permissions" I'm ok with the content of PR.

**Pull request merged**
