### PR TITLE
Bulk scan changes

### PR DESCRIPTION
**Pull request by tchow8**
BulkScan team are adjusting their required roles to match a new consistent approach. This PR gives all systemupdate role user (the previous role) permissions to the new role, divorce-caseworker-bulkscan.
When all the user migration is done in Production, we can phase out the existing systemupdate permissions.

https://tools.hmcts.net/jira/browse/DIV-5031

### CODE REVIEW

**Comment by qzhou-hmcts** [comment]
Does this PR has ticket associated?

**Comment by tchow8** [comment]
Not yet:
Simply had email communications from Bulk Scan team:

**Comment by tchow8** [comment]
I'll raise one myself for tracking

**Comment by tchow8** [comment]
Added ticket @qzhou-hmcts

**Comment by tchow8** [comment]
Yep, making this change so they can test before promoting to Prod. This PR does not remove the existing bulk scan role so it should continue working as is

**Pull request merged**
